# Language setting
language: none

env:
  matrix:
    - environment=integration
    - environment=production
    - environment=development
    #- environment=fail

build:
  ci:
    - echo "environment is $environment"
    - echo "job number is $JOB_NUMBER"
    - if [ "$environment" == "integration" ]; then sleep 2; fi
    - if [ "$environment" == "production" ]; then sleep 4; fi
    - if [ "$environment" == "development" ]; then sleep 8; fi
    #- if [ "$environment" == "fail" ]; then cd fakedir; fi

  on_success:
    - echo "push image with tag **$environment** here"
    - shipctl put_resource_state firstImage versionName $environment
  on_failure:
    - echo "Environment **$environment** failed to build"

integrations:
  hub:
    - integrationName: "trriplejay docker hub"
      type: hub

jobs:
  - name: afterJob
    type: runSh
    steps:
      - IN: firstImage
      - TASK:
          script:
            - sleep 5
            - echo "all done"
  - name: simpleserver_runCI
    type: runCI
    steps:
      - OUT: firstImage

resources:
  - name: firstImage
    type: image
    versionTemplate:
      sourceName: trriplejay/simpleserver
      versionName: setup1

  - name: secondImage
    type: image
    versionTemplate:
      sourceName: trriplejay/simpleserver
      versionName: setup2

  - name: thirdImage
    type: image
    versionTemplate:
      sourceName: trriplejay/simpleserver
      versionName: setup3
