# Language setting
language: node_js

# Version number
node_js:
  - 6.11.0

build:

  ci:
    - reqProcID=$(docker ps -q --filter name=reqProc)
    - docker commit $reqProcID trriplejay/shipctlenv:latest
    - docker push trriplejay/shipctlenv:latest
  post_ci:
    - echo "post_ci section"

  on_success:
    - echo "huzzah!"

  push:
    # - docker push gcr.io/sample-gke/simpleserver:$environment.$BUILD_NUMBER

integrations:
  hub:
    - integrationName: "trriplejay docker hub"
      type: dockerRegistryLogin
  # notifications:

    # - integrationName: imperialchat
    #   type: slack
    #   recipients:
    #     - "@trriplejay"
    #     - "#bot_scripts"
    #   on_success: always
    #   on_failure: never

    # - integrationName: "imperialchat failure"
    #   type: slack
    #   recipients:
    #     - "@trriplejay"
    #     - "#bot_scripts"
    #   on_success: never
    #   on_failure: always

    # - integrationName: email
    #   type: email
    #   recipients:
    #     - stockbauer@gmail.com

    #   on_success: always
    #   branches:
    #     only:
    #       - notifications

    # - integrationName: email
    #   type: email
    #   recipients:
    #     - stockbauer@gmail.com

    #   on_success: never
    #   on_failure: always
    #   branches:
    #     only:
    #       - notifications


resources:
  - name: mySlack
    type: notification
    integration: imperialchat
    versionTemplate:
      recipients:
        - "@trriplejay"
        - "#bot_scripts"

  - name: myIRC
    type: notification
    versionTemplate:
      method: irc
      recipients:
        - "@trriplejay"
        - "#shippable"
        - "#imperialchat"

  - name: myWebhookPayload
    type: notification
    integration: testGenericHook


jobs:
  - name: simpleserver_runCI
    type: runCI
    steps:
      - IN: mySlack
      - IN: myIRC
      - IN: myWebhookPayload