tags:
  simple_api: ${res_punchh_cd_bundle_distributed_simple_api}
  simple_ui: ${res_punchh_cd_bundle_distributed_simple_ui}
  simple_notification: ${res_punchh_cd_bundle_distributed_simple_notification}
  simple_test: ${res_punchh_cd_bundle_distributed_simple_test}